name: Build

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: zmkfirmware/zmk-build-arm:3.5
      options: --user root

    strategy:
      fail-fast: false
      matrix:
        include:
          - board: seeeduino_xiao_ble
            shield: tiny18mini_l
          - board: seeeduino_xiao_ble
            shield: tiny18mini_r

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cache west modules
        uses: actions/cache@v4
        with:
          path: |
            bootloader/
            modules/
            tools/
            zephyr/
            zmk/
          key: west-modules-${{ hashFiles('''config/west.yml''') }}
          restore-keys: |
            west-modules-

      - name: West Init
        run: west init -l config

      - name: West Update
        run: west update

      - name: West Build
        run: west build -p -s zmk/app -b ${{ matrix.board }} -d build/${{ matrix.shield }} -- -DSHIELD=${{ matrix.shield }}
      
      - name: Archive firmware
        uses: actions/upload-artifact@v4
        with:
          name: firmware-${{ matrix.shield }}
          path: |
            build/${{ matrix.shield }}/zephyr/zmk.uf2